### ISSUE TITLE
Command-c save does not save diagram

### ISSUE THREAD

**Issue by jimraynor0** [mike-goodwin/owasp-threat-dragon-desktop#43] opened 2019-01-24 02:26 UTC
Reproduce steps:

1. Create a new threat model
2. Add a new diagram
3. Save
4. Edit diagram
5. Add a process to the diagram
6. Hit command+s
7. Hit command+o, open the previously saved threat model
8. Edit diagram again

Expected behavior: 
  Diagram should contain one process

Actual behavior:
  Diagram is empty

**Comment by josephthweatt** [comment] 2019-06-14 16:01
I am experiencing the same issue. Additional details:
- Using Mac
- Downloaded `threatdragon-darwin-x64.zip` from 0.1.26 
- I used command+s to save, although I noticed the command to save in Threatdragon is command+c for some reason. In any case neither work.
- Creating a new file after editing the project basically just copies the initial project, so you just get a duplicate project with no saved edits.
- On one occasion Threatdragon deleted my project's json, leaving the file with a single `null` value in it.

Is there any plan to resolve this soon?

**Comment by mike-goodwin** [comment] 2019-06-14 19:01
Thanks for submitting this  - I'm looking into it. In the meantime, your workaround is to use the save button on the diagram editor. This correctly saves the diagrams as far as I can tell.

**Comment by mike-goodwin** [comment] 2019-06-14 22:28
The original issue from @jimraynor0 - diagram not saving is fixed in and will be included in the next desktop release. Note currently this is tested only on Windows since I don;t have access to a Mac at the moment. Also, from the same commit save is now Ctrl-S or command-S like the rest of the civilised world ;)

I believe the 3rd bullet point in the comment from @josephthweatt is also fixed, but I was not exactly clear on the steps to reproduce so please re-open this or a new issue if you find it is still broken when the release comes out.

Also note: Autoupdate is not working for the Mac version because I don't have a code signing cert still so you will have to manually download the new version v0.1.28 when it is released.

**Closed by mike-goodwin** 2019-06-14 22:28 UTC
